#!/bin/env bash
# Check if number of arguments is correct
if [ $# -ne 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

file_path=$1
ip_address=$2
username=$3
ssh_key=$4

if [ ! -f "$file_path" ]; then
  echo "Error: $file_path is not a file"
  exit 1
fi

# Disable strict host key checking
ssh_options="-o StrictHostKeyChecking=no"

# Transfer the file to the user's home directory
scp "$ssh_options" -i "$ssh_key" "$file_path" "$username@$ip_address:~/"

if ssh "$ssh_options" -i "$ssh_key" "$username@$ip_address" "test -f ~/${file_path##*/}"; then
  echo "File transfer successful"
else
  echo "Error: file transfer failed"
  exit 1
fi
