#!/bin/env bash
# Check if number of arguments is correct
if [ $# -lt 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

# Assign arguments to variables
FILE_PATH=$1
SERVER_IP=$2
USERNAME=$3
SSH_KEY_PATH=$4

# Use scp to transfer file to server
scp -o "StrictHostKeyChecking no" -i "$SSH_KEY_PATH" "$FILE_PATH" "$USERNAME@$SERVER_IP:~/"

# Check if scp command was successful
if [ $? -eq 0 ]
then
  echo "File transfer successful!"
else
  echo "File transfer failed."
fi
