#!/usr/bin/env bash

# Update the package list and install Nginx
sudo apt-get update
sudo apt-get -y install nginx

# Create a default configuration file
sudo mkdir -p /var/www/html
sudo chown -R ubuntu:ubuntu /var/www/html
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo unlink /etc/nginx/sites-enabled/default
sudo echo "server {
    listen 80;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm;
    server_name _;
}" | sudo tee /etc/nginx/sites-available/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
# Configure the redirection
sudo sed -i '/listen \[::\]:80 default_server;/a \\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n' /etc/nginx/sites-available/default
sudo service nginx restart
