#!/usr/bin/env bash
# Install nginx web server
sudo apt-get update
sudo apt-get -y install nginx

# Configure custom 404 error page
sudo sed -i 's|#error_page 404 /404.html;|error_page 404 /404.html;
        location = /404.html {
                internal;
                root /usr/share/nginx/html;
                echo "Ceci n'\''est pas une page.";
}|' /etc/nginx/sites-available/default

# Restart nginx to apply changes
sudo service nginx restart
