#!/usr/bin/env bash
# Configure Nginx to include custom response header
sudo apt update && sudo apt upgrade -y

sudo apt install nginx -y

sudo sed -i '/http {/a \\tadd_header X-Served-By $hostname;' /etc/nginx/nginx.conf

sudo systemctl restart nginx
