#!/usr/bin/env bash
# Configure Nginx to include custom response header
sudo sed -i '/location \/ {/a \       add_header X-Served-By $hostname;' /etc/nginx/sites-available/default
sudo systemctl restart nginx
