#!/usr/bin/env bash
# This script installs and configures HAproxy on a new Ubuntu machine to distribute traffic to web-01 and web-02 using roundrobin algorithm

if ! command -v haproxy &> /dev/null
then
    sudo apt-get update
    sudo apt-get install -y haproxy
fi

cat <<EOF | sudo tee /etc/haproxy/haproxy.cfg > /dev/null
frontend www
    bind *:80
    mode http
    default_backend servers

backend servers
    mode http
    balance roundrobin
    server web-01 127342-web-01:80 check
    server web-02 127342-web-02:80 check
EOF

sudo systemctl enable haproxy.service

sudo systemctl restart haproxy.service
