#!/usr/bin/env bash
#Bash script that displays listening port

echo "Active Internet connections (only servers)"
echo "Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name"

# -lnp options: display listening sockets, numeric ports, process name and PID
ss -lnp | awk '
/tcp/ {
  gsub("[*:]","")
  printf("tcp %-6s %-6s %-23s %-23s %-13s %s/%s\n", $5, $6, $4, $3, $1, $7, $8)
}
/udp/ {
  gsub("[*:]","")
  printf("udp %-6s %-6s %-23s %-23s %-13s %s/%s\n", $5, $6, $4, $3, $1, $7, $8)
}'

echo "Active UNIX domain sockets (only servers)"
echo "Proto RefCnt Flags       Type       State         I-Node   PID/Program name    Path"

# -x option: show UNIX sockets
ss -xlp | awk '
/\// {
  printf("unix %-6s %-10s %-11s %-13s %-7s %s/%s %s\n", $1, $2, $3, $4, $5, $6, $7, $8)
}'
