#!/usr/bin/env bash
# This script configures Nginx to listen on port 80.

sudo apt-get update
sudo apt-get install -y nginx
sudo apt-get install systemd

sudo sed -i 's/listen \[::\]:80 default_server;/listen 80 default_server;/g' /etc/nginx/sites-available/default

sudo service restart nginx
