#!/usr/bin/env bash
# This script configures Nginx to listen on port 80.

cd /etc/nginx/sites-enabled/ || exit;
rm default;
ln -s /etc/nginx/sites-available/default default;
sudo service nginx restart
