#!/usr/bin/env bash
# shellcheck disable=SC2009
#Bash script that displays the PID, along with the process name
PID_LIST=$(pgrep -f "bash")

for PID in $PID_LIST; do
    PROCESS_NAME=$(cat /proc/$((PID))/comm)
    echo "$PID $PROCESS_NAME"
done
