#!/usr/bin/env bash
#Bash script that displays content of the file /etc/passwd

while read -r line
do
    IFS=':' read -r -a array <<< "$line"
    echo "${array[0]}:${array[2]}:${array[5]}"
done < /etc/passwd
