#!/usr/bin/env bash
# Bash script that prints "Best School" & "Hi" at 9

counter=1
while [ $counter -le 10 ]
do
    if [ $counter -eq 9 ]
    then
        echo "Hi"
    else
        echo "Best School"
    fi
    counter=$((counter+1))
done
