#!/usr/bin/env bash
# Bash script that displays the timer for 12hrs and 59min

hours=0
minutes=1
while [ $hours -le 12 ]
do
    echo "Hour: $hours"
    while [ $minutes -le 59 ]
    do
        echo "$minutes"
        minutes=$((minutes+1))
    done
    hours=$((hours+1))
    minutes=1
done
