#!/usr/bin/env bash
#Bash script to change IP address

echo "127.0.0.2 localhost" | sudo tee /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts

#sudo service docker restart
cat ~/hosts.new | sudo tee /etc/hosts
