#!/usr/bin/env bash
#Bash script to change IP address

echo "127.0.0.2 localhost" | sudo tee ~/hosts.new
echo "8.8.8.8 facebook.com" | sudo tee -a /hosts.new

#sudo service docker restart
sudo cp /etc/hosts /etc/hosts.bak
sudo rm /etc/hosts
sudo cp ~/hosts.new /etc/hosts
