#!/usr/bin/env bash
# Get all network interfaces

interfaces=$(ifconfig | awk -F':' '/^[a-z]/ {print $1}')

# Loop through each interface
for interface in $interfaces; do
  # Get IP address of the interface
  ip=$(ifconfig "$interface" | awk '/inet / {print $2}')
  echo "$ip"
done
