#!/usr/bin/env bash
# Get the PID of the Gunicorn process
if pgrep -x "gunicorn" > /dev/null; then
    echo "Gunicorn reloaded successfully"

    worker_pids=$(pgrep -x gunicorn)

    for pid in $worker_pids; do
        kill -HUP "$pid"
    done
fi
