#!/usr/bin/env bash
# Get the PID of the Gunicorn process
master_pid=$(pgrep -o -x gunicorn)

# Check if Gunicorn is running
if [ -z "$master_pid" ]; then
  echo "Gunicorn is not running."
  exit 1
fi

# Send a graceful reload signal to the master process
kill -s HUP "$master_pid"
